<?php
/**
 * Created by PhpStorm.
 * User: dale047
 * Date: 2019/3/30
 * Time: 下午8:12
 */
namespace app\admin\controller;
use think\Controller;
use think\Request;
use app\common\lib;

class Common extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        /*网站名称*/
        $SiteName = Model('Config')->getSiteName();
        /*站点版权名称*/
        $SiteCopy = Model('Config')->getSiteCopy();
        /*站点归属学院名称*/
        $SiteCollege = Model('Config')->getSiteCollege();
        /*站点首页提示*/
        $BannerTip = Model('Config')->getBannerTip();
        /*判断用户是否登录*/
        $res = $this->isLogin();
        if(!$res){
            return $this->error('请登录后操作',url('admin/login/index'));
        }
        /*登录的所有信息*/
        $getLoginUserInfo = $this->getLoginUserInfo();
        /*统计登录*/
        $countLogin = Model('AdminLogin')->countLogin();
        /*服务器信息*/
        $info = $this->ServerInfo();
        /*当前登录所有信息*/
        $LoginUser = $this->getLoginUser();
        $this->assign([
            'LoginInfo' => $getLoginUserInfo,
            'countLogin' => $countLogin,
            'SiteName' => $SiteName,
            'SiteCopy' => $SiteCopy,
            'SiteCollege' => $SiteCollege,
            'BannerTip' => $BannerTip,
            'serverInfo' => $info,
            'LoginUser' => $LoginUser
        ]);
    }

    public function isLogin()
    {
        $userInfo = session(config('AdminLogin.Login_Start'),'',config('AdminLogin.Login_End'));
        if(!$userInfo){
            return false;
        }
        return true;
    }

    public function getLoginUser()
    {
        $userInfo = session(config('AdminLogin.Login_Start'),'',config('AdminLogin.Login_End'));
        return $userInfo;
    }

    public function getLoginUserInfo()
    {
        $userInfo = $this->getLoginUser();
        $userLoginInfo = Model('AdminLogin')->getLastLogin($userInfo['username']);
        return $userLoginInfo;
    }

    public function ServerInfo()
    {
        $info = [
            '操作系统' => PHP_OS,
            '运行环境' => $_SERVER['SERVER_SOFTWARE'],
            'PHP 运行方式' => php_sapi_name(),
            'ThinkPHP 版本' => THINK_VERSION,
            '上传项目限制大小' => ini_get('upload_max_filesize'),
            '执行时间限制' => ini_get('max_execution_time').'s',
            '服务器时间' => date('Y-m-d H:i:s'),
            '服务器域名/IP' => $_SERVER['SERVER_NAME'],
            '剩余空间' => rand((disk_free_space(".")/(1024*1024)),2).'MB',
        ];
        return $info;
    }

    public function requestData()
    {
        $request = Request::instance();
        return $request;
    }

    public function checkLevel($id)
    {
        $level = Model('Lead')->get(['id'=>$id]);
        if(!($level['level'] == 1)){
            return false;
        }
        return true;
    }

    public function changeStatus()
    {
        $id = lib\Other::getId();
        $status = Request::instance()->param('status');
        $res = Model('Apphouse')->save(['status'=>$status],['id'=>$id]);
        if(!$res){
            return false;
        }
        return true;
    }
}