<?php
/**
 * Created by PhpStorm.
 * User: dale047
 * Date: 2019/3/28
 * Time: 下午2:46
 */

namespace app\index\controller;
use think\Controller;
use app\common\lib;

class Common extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        /*网站名称*/
        $SiteName = Model('Config')->getSiteName();
        /*站点版权名称*/
        $SiteCopy = Model('Config')->getSiteCopy();
        /*站点归属学院名称*/
        $SiteCollege = Model('Config')->getSiteCollege();
        /*站点首页提示*/
        $BannerTip = Model('Config')->getBannerTip();
        /*用户信息*/
        $user = $this->GetThisUser();
        $this->assign([
            'BannerTip'  => $BannerTip,
            'SiteName'   => $SiteName,
            'SiteCopy'   => $SiteCopy,
            'SiteCollege'=> $SiteCollege,
            'UserInfo'   => $user
        ]);
        /*站点导航栏*/
        $this->FirstNav();
    }

    public function isLogin()
    {
        $userInfo = session(config('CustomerLogin.session_user'),'',config('CustomerLogin.session_user_scope'));
        if(!$userInfo){
            return false;
        }
        return $userInfo;
    }

    public function SetPwd()
    {
        $lib = new lib\SetPassword();
        return $lib;
    }

    public function FirstNav()
    {
        /*获取所有['pid' => '0','level' => '1']菜单*/
        $FirstNav = Model('Lead')->getFirstNav();
        /*循环遍历二级*/
        foreach ($FirstNav as $k => $v) {
            $SecNav = Model('Lead')->getSecNav($v['id']);
            if($SecNav){
                $FirstNav[$k]['SecNav'] = $SecNav;
            }else{
                $FirstNav[$k]['SecNav'] = 0;
            }
        }
        /*导航级别赋值*/
        $this->assign('firstnav',$FirstNav);
    }

    public function GetThisUser()
    {
        $userInfo = $this->isLogin();
        $user = Model('Customer')->get(['id'=>$userInfo['id']]);
        return $user;
    }
}